%for use with python module https://github.com/dakota-palmer/medpc2excel/tree/RichardLab_config

%% load .xlsx generated by medpctoexcel python module
%cd to folder containing your .xlsx
cd 'Z:\Dakota\MEDPC\Downstairs\vp-vta-stgtacr_DStrain\Opto DS Task Test- CUE Laser Manipulation';

%default is 1 file per date, containing sheet for each subject (plus one extra)
fileList= dir('*.xlsx');

% for file=fileList
%     readtable(file.name)
% end

% readtable(fileList.name)
sessionCount= 1; %for indexing into struct. Multiple 'sessions' per .xlsx file
%here we'll have a struct with fields that have one row for every session.
%mirroring christelle's organization
for file= 1:numel(fileList)
    [~,sheet_name]=xlsfinfo(fileList(file).name); %one sheet per subject + first sheet 'MSNs'
    %remove the first sheet 'MSNs' (only concerned about raw data)
    sheet_name=sheet_name(2:end);
    
    %just putting into a struct, one row per session
    for subj= 1:numel(sheet_name)
        trainData(sessionCount).subject= sheet_name(subj); 
        trainData(sessionCount).file= fileList(file).name;
        
        %read the excel sheet and extract variables
        MPCraw= readtable(fileList(file).name, 'Sheet', cell2mat(sheet_name(subj)));
        
        varNames= MPCraw.Properties.VariableNames; %get var labels
        for var = 1:numel(varNames)
            trainData(sessionCount).(varNames{var})= MPCraw(:,var);
        end
        
        sessionCount= sessionCount+1; %iterate sessionCount 
    end
end

